spring.application.name=servicioConsultas

#Configuraciones para el servidor de configuracion
spring.cloud.config.enabled=true
spring.profiles.active=dev
spring.config.import=configserver:http://localhost:8888

#Configuraciones de redis server
#spring.redis.host=redis
#spring.redis.port=6379
#spring.redis.password=
#spring.redis.timeout=5000