spring.application.name=eurekaServer

#Configuraciones para el servidor de configuracion
spring.cloud.config.enabled=true
spring.profiles.active=dev
spring.config.import=configserver:http://localhost:8888